In [1]:
1+1

2

In [ ]:
%pip install numpy pandas scikit-learn torch torchvision transformers 

In [3]:
import numpy as np

# Arrays

- $n$-dimensional arrays


In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.zeros((3,4)) # three rows,  four columns with zeros
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones((2,3)) # with ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((9,9), 7) # fill with 7

array([[7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [ ]:
np.arange(0, 12, 2) # start, stop, step , stop is excluding

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.arange(0, 1.25, 0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,1, 5) # start, step, number of points 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Identity matrix 
np.eye(6) 

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
x = np.eye(6)
# properties of arrays 

print("Shape:", x.shape) # (number of rows, number of columns)
print("Ndim:", x.ndim)  # 2
print("Size:", x.size) # number of elements
print("DType:", x.dtype) # data type

Shape: (6, 6)
Ndim: 2
Size: 36
DType: float64


# Indexing and slicing

In [22]:
v = np.array([10,20,30,40]) # 1D
print(v[0]) # first element 
print(v[-1]) # last element (Python feature)
print(v[1:3]) # from second to third 

10
40
[20 30]


In [34]:
m = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
    ]
)

m[0,1] # first row, second column
m[:, 0] # first column
m[1,:] # second row 
m[0:2, 1:3] # submatrix 

array([[2, 3],
       [5, 6]])

In [29]:
import math
x = 0.1 + 0.2
math.isclose(x,0.3) 

True

In [37]:
# Boolean indexing 
v = np.array([1,5,2,8,3])
mask = v > 3
v[mask] 
v[v>3]

array([5, 8])

In [63]:
# vectorized operations (the MATLAB-Numpy-Way)

a = np.array([1,2,3])
b = np.array([10,20,30])

a + b
a * b
a ** 0.25 # ** ... to the power of ..
#np.sqrt(a)

array([1.        , 1.18920712, 1.31607401])

In [43]:
def array_plus(x,y):
    if len(x) == len(y):
        new = []
        for i in range(len(x)):
            new.append(x[i] + y[i])
        return new
    else:
        print("dimesion must be the same")

x = [1,2,3]
y = [10,20,30]
array_plus(x,y)

[11, 22, 33]

In [56]:
import time

x = list(range(100000000))
y = list(range(100000000))
start = time.time()

array_plus(x,y)
end = time.time()

print("non-vectorized",end - start)

x = np.array(x)
y = np.array(y)

start = time.time()

x+y

end = time.time()

print("vectorized",end - start)

non-vectorized 3.9234611988067627
vectorized 0.022266864776611328


In [57]:
3.92 / 0.02

196.0

In [55]:
np.array(x)

array([       0,        1,        2, ..., 99999997, 99999998, 99999999],
      shape=(100000000,))

In [70]:
# Aggregation and statistics

x = np.array(
    [
        [1,2,3],
        [4,5,6],
    ] 
)
x.sum() # sum of all element
x.sum(axis=0) # sum per column: 5, 7, 9 , sum of the rows
x.sum(axis=1) # sum per row: 6,15 , sum of the columns 

x.mean(axis=0)
x.min()
x.max()
np.median(x) 


np.float64(3.5)

In [77]:
# Reshaping

a = np.arange(12) # [0..11]
m = a.reshape(2,6)
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [78]:
# transposing
m.T

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [83]:
m.flatten().reshape(-1,1) # column vector
m.flatten().reshape(1,-1) # row vector

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [85]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate([b,a])

array([4, 5, 6, 1, 2, 3])

In [86]:
np.stack([b,a])

array([[4, 5, 6],
       [1, 2, 3]])

In [ ]:
np.hstack([b,a]) # horizontal stack

array([4, 5, 6, 1, 2, 3])

In [ ]:
np.vstack([b,a]) # vertical stack 

array([[4, 5, 6],
       [1, 2, 3]])

# Linear algebra

In [89]:
A = np.array(
    [
        [1,2],
        [4,5],
    ] 
)

B = np.array(
    [
        [10,20],
        [40,50],
    ] 
)

A*B # elementwise 

array([[ 10,  40],
       [160, 250]])

In [93]:
# matrix multiplication
A @ B 
# or
np.matmul(A,B)

array([[ 90, 120],
       [240, 330]])

In [ ]:
np.linalg.det(A) # determinant
np.linalg.inv(A) # matrix inversion

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [ ]:
np.array([1,2,3]) @ np.array([1,2,3]) 

np.int64(14)